import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
	sidebar: [
		"getting-started",
		{
			type: "category",
			label: "Concepts",
			link: { type: "doc", id: "concepts/index" },
			collapsible: true,
			collapsed: false,
			items: [{ type: "autogenerated", dirName: "01-concepts" }],
		},
		{
			type: "category",
			label: "Guides",
			link: { type: "doc", id: "guides/index" },
			collapsible: true,
			collapsed: false,
			items: [{ type: "autogenerated", dirName: "02-guides" }],
		},
		{
			type: "category",
			label: "API",
			link: { type: "doc", id: "api/index" },
			collapsible: true,
			collapsed: false,
			items: [{ type: "autogenerated", dirName: "03-api" }],
		},
		{
			type: "category",
			label: "Examples",
			link: { type: "doc", id: "examples/index" },
			collapsible: true,
			collapsed: false,
			items: [{ type: "autogenerated", dirName: "04-examples" }],
		},
		// { type: "autogenerated", dirName: "." },
	],
};

export default sidebars;
